### ISSUE TITLE
What is dataset_parser.generator?

### ISSUE THREAD

**Issue by enomto** [dhkim0225/keras-image-segmentation#2]
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from dataset_parser.generator import data_generator
ImportError: No module named dataset_parser.generator

What error is it?How can I solve it?

**Comment by dhkim0225** [comment]
Sorry for the late reply. 
Perhaps this is caused by not adding the '\_\_init\_\_.py' file to the dataset_parser folder.

Please create an '\_\_init\_\_.py' empty file in the dataset_parser folder and run train.py again.
